/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiSeoRouteImport } from './routes/ai-seo'
import { Route as AppDevelopmentRouteImport } from './routes/app-development'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContentMarketingRouteImport } from './routes/content-marketing'
import { Route as ContentSocialMediaRouteImport } from './routes/content-social-media'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as GoogleAdsRouteImport } from './routes/google-ads'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as MetaAdsRouteImport } from './routes/meta-ads'
import { Route as PaidAdvertisingRouteImport } from './routes/paid-advertising'
import { Route as PpcManagementRouteImport } from './routes/ppc-management'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as SeoAiSearchRouteImport } from './routes/seo-ai-search'
import { Route as SocialMediaMarketingRouteImport } from './routes/social-media-marketing'
import { Route as WebAppDevelopmentRouteImport } from './routes/web-app-development'
import { Route as WebDevelopmentRouteImport } from './routes/web-development'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSeoRoute = AiSeoRouteImport.update({
  id: '/ai-seo',
  path: '/ai-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDevelopmentRoute = AppDevelopmentRouteImport.update({
  id: '/app-development',
  path: '/app-development',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentMarketingRoute = ContentMarketingRouteImport.update({
  id: '/content-marketing',
  path: '/content-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentSocialMediaRoute = ContentSocialMediaRouteImport.update({
  id: '/content-social-media',
  path: '/content-social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleAdsRoute = GoogleAdsRouteImport.update({
  id: '/google-ads',
  path: '/google-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaAdsRoute = MetaAdsRouteImport.update({
  id: '/meta-ads',
  path: '/meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const PaidAdvertisingRoute = PaidAdvertisingRouteImport.update({
  id: '/paid-advertising',
  path: '/paid-advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const PpcManagementRoute = PpcManagementRouteImport.update({
  id: '/ppc-management',
  path: '/ppc-management',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoAiSearchRoute = SeoAiSearchRouteImport.update({
  id: '/seo-ai-search',
  path: '/seo-ai-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaMarketingRoute = SocialMediaMarketingRouteImport.update({
  id: '/social-media-marketing',
  path: '/social-media-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const WebAppDevelopmentRoute = WebAppDevelopmentRouteImport.update({
  id: '/web-app-development',
  path: '/web-app-development',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDevelopmentRoute = WebDevelopmentRouteImport.update({
  id: '/web-development',
  path: '/web-development',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-seo': typeof AiSeoRoute
  '/app-development': typeof AppDevelopmentRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/content-marketing': typeof ContentMarketingRoute
  '/content-social-media': typeof ContentSocialMediaRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/google-ads': typeof GoogleAdsRoute
  '/insights': typeof InsightsRoute
  '/meta-ads': typeof MetaAdsRoute
  '/paid-advertising': typeof PaidAdvertisingRoute
  '/ppc-management': typeof PpcManagementRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/seo': typeof SeoRoute
  '/seo-ai-search': typeof SeoAiSearchRoute
  '/social-media-marketing': typeof SocialMediaMarketingRoute
  '/web-app-development': typeof WebAppDevelopmentRoute
  '/web-development': typeof WebDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-seo': typeof AiSeoRoute
  '/app-development': typeof AppDevelopmentRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/content-marketing': typeof ContentMarketingRoute
  '/content-social-media': typeof ContentSocialMediaRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/google-ads': typeof GoogleAdsRoute
  '/insights': typeof InsightsRoute
  '/meta-ads': typeof MetaAdsRoute
  '/paid-advertising': typeof PaidAdvertisingRoute
  '/ppc-management': typeof PpcManagementRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/seo': typeof SeoRoute
  '/seo-ai-search': typeof SeoAiSearchRoute
  '/social-media-marketing': typeof SocialMediaMarketingRoute
  '/web-app-development': typeof WebAppDevelopmentRoute
  '/web-development': typeof WebDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-seo': typeof AiSeoRoute
  '/app-development': typeof AppDevelopmentRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/content-marketing': typeof ContentMarketingRoute
  '/content-social-media': typeof ContentSocialMediaRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/google-ads': typeof GoogleAdsRoute
  '/insights': typeof InsightsRoute
  '/meta-ads': typeof MetaAdsRoute
  '/paid-advertising': typeof PaidAdvertisingRoute
  '/ppc-management': typeof PpcManagementRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/seo': typeof SeoRoute
  '/seo-ai-search': typeof SeoAiSearchRoute
  '/social-media-marketing': typeof SocialMediaMarketingRoute
  '/web-app-development': typeof WebAppDevelopmentRoute
  '/web-development': typeof WebDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-seo'
    | '/app-development'
    | '/case-studies'
    | '/contact'
    | '/content-marketing'
    | '/content-social-media'
    | '/digital-marketing'
    | '/google-ads'
    | '/insights'
    | '/meta-ads'
    | '/paid-advertising'
    | '/ppc-management'
    | '/privacy-policy'
    | '/seo'
    | '/seo-ai-search'
    | '/social-media-marketing'
    | '/web-app-development'
    | '/web-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-seo'
    | '/app-development'
    | '/case-studies'
    | '/contact'
    | '/content-marketing'
    | '/content-social-media'
    | '/digital-marketing'
    | '/google-ads'
    | '/insights'
    | '/meta-ads'
    | '/paid-advertising'
    | '/ppc-management'
    | '/privacy-policy'
    | '/seo'
    | '/seo-ai-search'
    | '/social-media-marketing'
    | '/web-app-development'
    | '/web-development'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-seo'
    | '/app-development'
    | '/case-studies'
    | '/contact'
    | '/content-marketing'
    | '/content-social-media'
    | '/digital-marketing'
    | '/google-ads'
    | '/insights'
    | '/meta-ads'
    | '/paid-advertising'
    | '/ppc-management'
    | '/privacy-policy'
    | '/seo'
    | '/seo-ai-search'
    | '/social-media-marketing'
    | '/web-app-development'
    | '/web-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiSeoRoute: typeof AiSeoRoute
  AppDevelopmentRoute: typeof AppDevelopmentRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  ContentMarketingRoute: typeof ContentMarketingRoute
  ContentSocialMediaRoute: typeof ContentSocialMediaRoute
  DigitalMarketingRoute: typeof DigitalMarketingRoute
  GoogleAdsRoute: typeof GoogleAdsRoute
  InsightsRoute: typeof InsightsRoute
  MetaAdsRoute: typeof MetaAdsRoute
  PaidAdvertisingRoute: typeof PaidAdvertisingRoute
  PpcManagementRoute: typeof PpcManagementRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SeoRoute: typeof SeoRoute
  SeoAiSearchRoute: typeof SeoAiSearchRoute
  SocialMediaMarketingRoute: typeof SocialMediaMarketingRoute
  WebAppDevelopmentRoute: typeof WebAppDevelopmentRoute
  WebDevelopmentRoute: typeof WebDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-seo': {
      id: '/ai-seo'
      path: '/ai-seo'
      fullPath: '/ai-seo'
      preLoaderRoute: typeof AiSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-development': {
      id: '/app-development'
      path: '/app-development'
      fullPath: '/app-development'
      preLoaderRoute: typeof AppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-marketing': {
      id: '/content-marketing'
      path: '/content-marketing'
      fullPath: '/content-marketing'
      preLoaderRoute: typeof ContentMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-social-media': {
      id: '/content-social-media'
      path: '/content-social-media'
      fullPath: '/content-social-media'
      preLoaderRoute: typeof ContentSocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-ads': {
      id: '/google-ads'
      path: '/google-ads'
      fullPath: '/google-ads'
      preLoaderRoute: typeof GoogleAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-ads': {
      id: '/meta-ads'
      path: '/meta-ads'
      fullPath: '/meta-ads'
      preLoaderRoute: typeof MetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid-advertising': {
      id: '/paid-advertising'
      path: '/paid-advertising'
      fullPath: '/paid-advertising'
      preLoaderRoute: typeof PaidAdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppc-management': {
      id: '/ppc-management'
      path: '/ppc-management'
      fullPath: '/ppc-management'
      preLoaderRoute: typeof PpcManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-ai-search': {
      id: '/seo-ai-search'
      path: '/seo-ai-search'
      fullPath: '/seo-ai-search'
      preLoaderRoute: typeof SeoAiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media-marketing': {
      id: '/social-media-marketing'
      path: '/social-media-marketing'
      fullPath: '/social-media-marketing'
      preLoaderRoute: typeof SocialMediaMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-app-development': {
      id: '/web-app-development'
      path: '/web-app-development'
      fullPath: '/web-app-development'
      preLoaderRoute: typeof WebAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-development': {
      id: '/web-development'
      path: '/web-development'
      fullPath: '/web-development'
      preLoaderRoute: typeof WebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiSeoRoute: AiSeoRoute,
  AppDevelopmentRoute: AppDevelopmentRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  ContentMarketingRoute: ContentMarketingRoute,
  ContentSocialMediaRoute: ContentSocialMediaRoute,
  DigitalMarketingRoute: DigitalMarketingRoute,
  GoogleAdsRoute: GoogleAdsRoute,
  InsightsRoute: InsightsRoute,
  MetaAdsRoute: MetaAdsRoute,
  PaidAdvertisingRoute: PaidAdvertisingRoute,
  PpcManagementRoute: PpcManagementRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SeoRoute: SeoRoute,
  SeoAiSearchRoute: SeoAiSearchRoute,
  SocialMediaMarketingRoute: SocialMediaMarketingRoute,
  WebAppDevelopmentRoute: WebAppDevelopmentRoute,
  WebDevelopmentRoute: WebDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
